name: san-cpu-env
channels:
- anaconda
- defaults
dependencies:
- cudatoolkit=8.0=1
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- cudnn=6.0.21=cuda8.0_0
- pip:
  - bleach==1.5.0
  - cycler==0.10.0
  - html5lib==0.9999999
  - markdown==2.6.9
  - matplotlib==2.0.2
  - numpy==1.13.1
  - pandas==0.20.3
  - protobuf==3.4.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.2
  - scikit-learn==0.19.0
  - scipy==0.19.1
  - six==1.10.0
  - tensorflow==1.3.0
  - tensorflow-tensorboard==0.1.4
  - werkzeug==0.12.2
prefix: /home/hubi/anaconda3/envs/raiden-3-env

